FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY frontend/package*.json ./

RUN npm install

COPY frontend ./

EXPOSE 3000

ENV NEXT_TELEMETRY_DISABLED 1
ENV WATCHPACK_POLLING true

CMD ["npm", "run", "dev"]
